export enum RestaurantSortBy {
  NAME_ASC = 'NAME_ASC',
  NAME_DESC = 'NAME_DESC',
  RATING_ASC = 'RATING_ASC',
  RATING_DESC = 'RATING_DESC',
  REVIEW_COUNT_ASC = 'REVIEW_COUNT_ASC',
  REVIEW_COUNT_DESC = 'REVIEW_COUNT_DESC',
}
