export enum OrderSortBy {
    CREATED_AT_ASC = "CREATED_AT_ASC",
    CREATED_AT_DESC = "CREATED_AT_DESC",
    PREFFERED_DELIVERY_DATE_ASC = "PREFFERED_DELIVERY_DATE_ASC",
    PREFFERED_DELIVERY_DATE_DESC = "PREFFERED_DELIVERY_DATE_DESC",
}