name: ASP.NET backend build and deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'Backend/**'
  workflow_dispatch:

env:
  DOTNET_VERSION: '5.0.x'
  WORKING_DIRECTORY: 'Backend'
  SQL_SERVER_URL: 'irestaurantserver.database.windows.net'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.WORKING_DIRECTORY }}
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{ env.WORKING_DIRECTORY }}
      
    - name: Publish IRestaurant.Auth
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/irestaurant/irestaurant-auth
      working-directory: ${{ env.WORKING_DIRECTORY }}/IRestaurant.Auth
    
    - name: Publish IRestaurant.WebAPI
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/irestaurant/irestaurant-webapi
      working-directory: ${{ env.WORKING_DIRECTORY }}/IRestaurant.WebAPI
      
    - name: Install EF Tool
      run: |
        dotnet new tool-manifest
        dotnet tool install dotnet-ef
      
    - name: Generate SQL script
      run: dotnet ef migrations script --output ${{env.DOTNET_ROOT}}/sql/sql-script.sql --idempotent --context ApplicationDbContext --project IRestaurant.DAL
      working-directory: ${{ env.WORKING_DIRECTORY }}
      
    - name: Deploy SQL script to Azure SQL database
      uses: Azure/sql-action@v1
      with:
        server-name: ${{ env.SQL_SERVER_URL }}
        connection-string: ${{ secrets.CONNECTION_STRING }}
        sql-file: ${{env.DOTNET_ROOT}}/sql/sql-script.sql
        
    - name: Deploy IRestaurant.Auth to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: IRestaurantAuth
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_IRESTAURANT_AUTH }}
        package: ${{env.DOTNET_ROOT}}/irestaurant/irestaurant-auth

    - name: Deploy IRestaurant.WebAPI to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: IRestaurantWebAPI
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_IRESTAURANT_WEBAPI }}
        package: ${{env.DOTNET_ROOT}}/irestaurant/irestaurant-webapi
