name: Angular frontend deploy

on:
  push:
    branches: [ main ]
    paths:
      - Frontend/**
  workflow_dispatch:
  
env:
  NODE_VERSION: '14.x'
  WEBAPP_PACKAGE_PATH: 'Frontend/irestaurant-angular-client/dist/irestaurant-angular-client'
  WORKING_DIRECTORY: 'Frontend/irestaurant-angular-client'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
  
    - name: Install dependencies
      run: npm ci
      working-directory: ${{ env.WORKING_DIRECTORY }}
    
    - name: Build
      run: npm run build
      working-directory: ${{ env.WORKING_DIRECTORY }}
      
    - name: Deploy Angular frontend to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: IRestaurant
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_IRESTAURANT }}
        package: ${{ env.WEBAPP_PACKAGE_PATH }}
