name: Angular client build, test and deploy

on:
  push:
    branches: [ main ]
    paths:
      - Frontend/**
  pull_request:
    branches: [ main ]
    paths:
      - Frontend/**
  workflow_dispatch:
  
env:
  NODE_VERSION: '14.x'
  WEBAPP_PACKAGE_PATH: './dist/irestaurant-angular-client'
  WORKING_DIRECTORY: 'Frontend/irestaurant-angular-client'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
  
    - run: npm ci
      working-directory: ${{ env.WORKING_DIRECTORY }}
      
    - run: npm run build --if-present
      working-directory: ${{ env.WORKING_DIRECTORY }}
      
    - name: Deploy Angular frontend to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: IRestaurantAuth
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AUTH }}
        package: ${{ env.WEBAPP_PACKAGE_PATH }}
