name: Angular frontend test

on:
  pull_request:
    branches: [ main ]
    paths:
      - Frontend/**
  workflow_dispatch:

env:
  NODE_VERSION: '14.x'
  WORKING_DIRECTORY: 'Frontend/irestaurant-angular-client'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Install dependencies
      run: npm ci
      working-directory: ${{ env.WORKING_DIRECTORY }}
      
    - name: Test
      run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      working-directory: ${{ env.WORKING_DIRECTORY }}
